### ISSUE TITLE
get log message from redux when running `react-snap`

### ISSUE THREAD

**Issue by achmadk** [stereobooster/react-snap#146]
[Reproducible example](https://github.com/achmadk/ticket-system)

In the latest release of react-snap, this repo successfully create html files from defined `Route` component from `react-router-dom`. Unfortunately, after that I got this log message when run `npm run build`

```
log: You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.
```
I have downgraded `react-snap` version but still got this log message. this log message still displayed after I have cleaned yarn's cache and deleted `node_modules` folder.

Maybe this log message is come from `react-chat-widget-angga` module which has internal redux store?

**Comment by stereobooster** [comment]
![screen shot 2018-02-22 at 15 08 22](https://user-images.githubusercontent.com/179534/36542828-448eef90-17e2-11e8-9576-8f25b972a90a.png)

seeing the same in browser console (using production build without react-snap), so this problem is not react-snap related.

In general every `log:..` line comes from application code not from `react-snap`
