### ISSUE TITLE
Build error with css link tag 

### ISSUE THREAD

**Issue by jasan-s** [stereobooster/react-snap#64]
I am using` inlineCss: true ` option

and and in my index.html i have a link tag: 
`    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.12/semantic.min.css">
`
I keep getting this error at build: 

```
Error: Evaluation failed: Error: https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.12/semantic.min.css
not in stylesheetAstObjects!
 at links.filter.forEach.stylesheet (<anonymous>:126:21)
 at Array.forEach (<anonymous>)
 at <anonymous>:124:12
```

**Comment by stereobooster** [comment]
This semantic-ui is a buggy thing https://github.com/stereobooster/react-snap/issues/27. Can you create small reproducible example?

Also need to warn you that this is bug in https://github.com/peterbe/minimalcss, even if it will be fixed in minimalcss I will need to update puppeteer before I will be able to update minimalcss.

**Comment by stereobooster** [comment]
Closing due inactivity. Feel free to reopen if you have reproducible example

**Comment by stereobooster** [comment]
can be connected to https://github.com/peterbe/minimalcss/issues/70
